# Generated by Django 4.0.4 on 2022-07-14 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiking_trails_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hikingtrails',
            old_name='all_trails_link',
            new_name='wta_link',
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='google_maps_directions',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='lon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hikingtrails',
            name='trail_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
